"""Chat-style PRD editing — narrow recognized intents + an honest fallback."""
from app.pipeline.prd_editor import apply_edit_instruction, restore_untouched_lines, to_ascii

SAMPLE = """# Fix: something\n\n## 5. Proposed Solution\n- FR-1: **[FR candidate]** do the first thing\n- FR-2: **[FR candidate]** do the second thing\n\n## 8. Open Questions\n- something to confirm\n"""


def test_title_rename():
    result = apply_edit_instruction(SAMPLE, "title: New Title Here")
    assert result.applied
    assert result.markdown.splitlines()[0] == "# New Title Here"


def test_remove_existing_fr():
    result = apply_edit_instruction(SAMPLE, "remove FR-2")
    assert result.applied
    assert "FR-2" not in result.markdown
    assert "FR-1" in result.markdown


def test_remove_missing_fr_is_honest_not_silent():
    result = apply_edit_instruction(SAMPLE, "delete FR-99")
    assert not result.applied
    assert "FR-99" in result.reply
    assert result.markdown == SAMPLE


def test_unrecognized_request_is_flagged_not_fabricated():
    result = apply_edit_instruction(SAMPLE, "make this more exciting")
    assert not result.applied
    assert "couldn't apply that rewrite" in result.reply
    assert "no model is available" in result.reply
    assert "make this more exciting" in result.markdown


# ---- the LLM tier -------------------------------------------------------------

REVISED = (SAMPLE.replace("do the first thing", "do the first thing, measured weekly")
           + "\n## 9. Rollout\n" + "- Phase 1: 10% of rx_gated orders, then widen if the metric holds\n" * 4)


def _llm_returning(markdown):
    calls = []
    def llm(ctx):
        calls.append(ctx)
        return {"prd_markdown": markdown, "reply": "Updated Section 7 with measurable metrics."}
    llm.calls = calls
    return llm


def test_a_plain_language_request_is_rewritten_by_the_model():
    llm = _llm_returning(REVISED)
    result = apply_edit_instruction(SAMPLE, "make the success metrics measurable", llm)
    assert result.applied
    assert "do the first thing, measured weekly" in result.markdown
    assert result.reply.startswith("Updated Section 7 with measurable metrics.")
    assert "still a DRAFT" in result.reply
    sent = llm.calls[0]["edit_inputs"]
    assert sent == {"original_markdown": SAMPLE, "instruction": "make the success metrics measurable"}


def test_the_draft_banner_is_ours_and_comes_back_if_the_model_drops_it():
    banner = "> **DRAFT — needs human review.** Generated by CareLoop run `16`."
    original = SAMPLE.replace("# Fix: something", "# Fix: something\n\n" + banner, 1)
    stripped = REVISED                       # no banner line at all
    result = apply_edit_instruction(original, "tighten the wording", _llm_returning(stripped))
    assert result.applied
    assert banner in result.markdown
    assert result.markdown.splitlines()[0].startswith("# ")


def test_a_rewrite_that_invents_a_number_is_rejected_and_flagged():
    invented = REVISED + "\n\nThis will recover 12345 orders per week.\n"
    result = apply_edit_instruction(SAMPLE, "add a target", _llm_returning(invented))
    assert not result.applied
    assert "12345" in result.reply and "not in the document" in result.reply
    assert result.markdown.startswith(SAMPLE.rstrip())            # document untouched
    assert "Reviewer request (unresolved):** add a target" in result.markdown


UNICODE_DOC = """# Fix: something

> **DRAFT — needs human review.** Generated by CareLoop run `11` on `2026-08-06`–`2026-09-05`.

## 3. Functional Requirements
- FR-1: produce region × lead_time and region × transaction_source cross-tabs
- FR-2: **[FR candidate]** do the second thing

## 8. Open Questions
- something to confirm
"""


def test_the_model_is_handed_an_ascii_only_document():
    """gpt-5-mini under strict JSON output mangles non-ASCII it must copy verbatim
    (em dash -> \\x14, en dash -> \\x13, x-sign -> a broken escape; Langfuse trace,
    run 11). So it never sees any: same words and numbers, ASCII punctuation."""
    llm = _llm_returning(REVISED)
    apply_edit_instruction(UNICODE_DOC, "tighten the wording", llm)
    sent = llm.calls[0]["edit_inputs"]["original_markdown"]
    assert sent.isascii()
    assert "DRAFT - needs human review" in sent and "region x lead_time" in sent
    assert "2026-08-06`-`2026-09-05" in sent


def test_untouched_lines_come_back_with_our_own_punctuation():
    """Whatever the model returned for a line it did not change — the ASCII copy or a
    corrupted one — the original line is restored, so the banner keeps its em dash."""
    model_out = to_ascii(UNICODE_DOC).replace(
        "- FR-1: produce region x lead_time and region x transaction_source cross-tabs",
        "- FR-1: produce region \x0d lead_time and region \x00d transaction_source cross-tabs",
    ) + "\nHow identified: the CareLoop run surfaced it.\n" * 12
    result = apply_edit_instruction(UNICODE_DOC, "how was this problem identified", _llm_returning(model_out))
    assert result.applied, result.reply
    assert "> **DRAFT — needs human review.** Generated by CareLoop run `11` on `2026-08-06`–`2026-09-05`." in result.markdown
    assert "region × lead_time and region × transaction_source" in result.markdown
    assert "How identified: the CareLoop run surfaced it." in result.markdown
    assert "\x0d" not in result.markdown and "\x00" not in result.markdown


def test_known_low_byte_corruption_in_new_text_is_repaired():
    corrupted = REVISED[:-1] + " and a dash the model wrote itself: \x14 right there \x13 too.\n"
    result = apply_edit_instruction(SAMPLE, "make this more exciting", _llm_returning(corrupted))
    assert result.applied
    assert "wrote itself: — right there – too." in result.markdown


def test_unrepairable_control_bytes_in_new_text_are_still_rejected():
    corrupted = REVISED[:-1] + " and a byte we cannot map: \x01 right there.\n"
    result = apply_edit_instruction(SAMPLE, "make this more exciting", _llm_returning(corrupted))
    assert not result.applied
    assert "corrupted characters" in result.reply


def test_restore_never_reverts_a_line_the_model_actually_changed():
    original = "- FR-1: do the first thing\n- FR-2: do the second thing\n"
    revised = "- FR-1: do the first thing weekly\n- FR-2: do the second thing\n"
    assert restore_untouched_lines(original, revised) == revised


def test_a_json_double_encoded_rewrite_is_unwrapped_and_accepted():
    """A live call was observed returning prd_markdown as its own json.dumps()
    output (escaped \\n, wrapping quotes) instead of the real text — reproduced
    on a real run's PRDs. Must decode it rather than shipping (or rejecting on
    length grounds) one giant unbroken line."""
    import json
    wrapped = json.dumps(REVISED)
    result = apply_edit_instruction(SAMPLE, "make this more exciting", _llm_returning(wrapped))
    assert result.applied
    assert result.markdown == REVISED.strip()
    assert "\n" in result.markdown


def test_a_failed_model_call_falls_back_honestly():
    def boom(ctx):
        raise RuntimeError("sphere FAILED")
    result = apply_edit_instruction(SAMPLE, "rewrite the overview", boom)
    assert not result.applied
    assert "the model call failed (RuntimeError)" in result.reply


def test_fast_paths_never_spend_a_model_call():
    llm = _llm_returning(REVISED)
    apply_edit_instruction(SAMPLE, "title: Better title", llm)
    apply_edit_instruction(SAMPLE, "remove FR-1", llm)
    assert llm.calls == []

