import { CodeGap, Finding, Remedy, RunState } from './run-state';

/**
 * The backend now returns the generated PRD as markdown (`prd_markdown` on
 * RunDetailResponse, surfaced as `RunState.prd_draft`), so on a live run the
 * drawer renders that directly — it is the real artifact the PRD Generator
 * wrote, not a client-side reconstruction.
 *
 * buildPrdView() is the FIXTURE-MODE fallback for when `prd_draft` is null:
 * it assembles an equivalent structured view from findings + code_gaps, both
 * of which are real. Prefer the markdown whenever it is present.
 */
export interface PrdView {
  banner: string;
  title: string;
  subtitle: string;
  overview: string;
  goals: [string, string][];
  requirements: [string, string][];
  openQuestions: [string, string][];
  channel: string;
}

/**
 * `rank` selects which finding this PRD is drafted for — defaults to the #1
 * ranked finding (the original, single-PRD behaviour). Passing another rank
 * (multi-PRD mode) re-titles from that finding's hypothesis and scopes the
 * functional-requirements list to only that finding's code gap(s), instead
 * of the pre-multi-PRD bug where every reconstructed PRD listed every gap's
 * remedies regardless of which finding it was drafted for.
 */
export function buildPrdView(run: RunState, rank = 1): PrdView {
  const journey = (run as unknown as { journey?: string }).journey ?? 'pd_checkout';
  const sorted = [...run.findings].sort((a, b) => a.rank - b.rank);
  const top = sorted.find((f) => f.rank === rank) ?? sorted[0];
  const topGap = run.code_gaps.find((g) => g.finding_rank === top?.rank && g.mechanism_found)
    ?? run.code_gaps.find((g) => g.mechanism_found);

  return {
    banner: `DRAFT — generated by run #${run.run_id}, needs human review`,
    /* The demo's #1 PRD keeps its curated name only on the pharmacy journey;
       every other journey/rank is titled from its own finding, so a homecare
       run never shows a "Pharmacy Checkout" card (seen on run 49). */
    title: top && !(top.rank === 1 && journey === 'pd_checkout')
      ? `Fix: ${top.hypothesis.split('.')[0].slice(0, 80)}`
      : 'Pharmacy Checkout Rescue',
    subtitle: buildSubtitle(run, topGap),
    overview: buildOverview(top, topGap),
    goals: [
      ['Recover rx-gated abandons', 'recover 5% ≈ 3,400 delivered orders/week in the 79%-of-GMV segment'],
      ['Separate real abandons from artifacts', 'exclude address-change re-creates from the abandon count'],
      ['No increase in support contacts', 'payment/refund ticket volume flat or down'],
    ],
    requirements: buildRequirements(run, top?.rank),
    openQuestions: [
      ['What is timeToAbandonOrderInMinutes set to in prod?', 'timor/oms — config-driven, not in source'],
      [
        'Can sendCommunication be called from abandonOrderV2 directly, or does it need adapting for the timer-driven path?',
        'timor/oms — Code Scout verified it exists in the same file but not wired into this path',
      ],
      ['Can a resume link re-attach an existing eRx, or does it force a new consult?', 'bintan/consultation'],
      ['Are address-change re-creates linkable to the original cart?', 'timor/oms'],
    ],
    channel: '#funnel-hackathon',
  };
}

function buildSubtitle(run: RunState, gap: CodeGap | undefined): string {
  const ranks = run.findings.map((f) => `#${f.rank}`).join(', ');
  const remedies = run.code_gaps.reduce((n, g) => n + (g.remedies?.length ?? 0), 0);
  const gapPart = gap ? `${gap.repo} ${gap.file}:${gap.line}` : 'no mechanism pinned';
  return `Agent suggestions · cites finding ${ranks} · ${gapPart} · ${remedies} remedy verdict(s)`;
}

function buildOverview(top: Finding | undefined, gap: CodeGap | undefined): string {
  if (!top) return 'No findings on this run.';
  if (!gap) return `${top.hypothesis}. Code Scout did not pin a mechanism for this finding.`;
  return `${top.hypothesis}. ${gap.gap_statement}`;
}

/** FR rows come from the Remedy Loop's own proposals, so the PRD mirrors what
 *  Code Scout actually searched for rather than a hand-written list.
 *
 *  Each row states the strength of its own evidence — an unverified remedy is
 *  a candidate to check, not a confirmed gap to build (PR #5, B3), and a
 *  not-found one says how many searches back that claim (B2). */
function buildRequirements(run: RunState, rank?: number): [string, string][] {
  const rows: [string, string][] = [];
  let n = 1;
  const order = (s: Remedy['status']) => (s === 'absent' ? 0 : s === 'partial' ? 1 : s === 'exists' ? 3 : 2);
  const gapsInScope = run.code_gaps.filter(
    (g) => g.mechanism_found && (rank == null || g.finding_rank === rank)
  );

  for (const gap of gapsInScope) {
    for (const r of [...(gap.remedies ?? [])].sort((a, b) => order(a.status) - order(b.status))) {
      const searches = r.searched_terms?.length ?? 0;
      const prefix =
        r.status === 'absent'
          ? `Not found in ${gap.repo} across ${searches} search${searches === 1 ? '' : 'es'}. `
          : r.status === 'partial'
            ? 'Partial match — related code exists, confirm before building. '
            : r.status === 'exists'
              ? 'Already present — verify before building. '
              : 'Not verified by the loop — check this one first. ';
      rows.push([`FR-${n++}`, `${prefix}${r.proposal}`]);
    }
  }
  if (!rows.length) rows.push([`FR-${n++}`, 'No verified remedies on this run — Code Scout pinned no mechanism.']);
  rows.push([`FR-${n++}`, 'Register the predicted recovery range before rollout; report realised vs predicted in the following run.']);
  return rows;
}

/**
 * Markdown -> HTML for the PRD Generator's real artifact, rendered in the
 * drawer's section bodies.
 *
 * Escapes first, so this is safe to bind with [innerHTML] even though the
 * source is server-generated text that interpolates finding hypotheses and
 * VoC quotes.
 *
 * Scope is what the PRDs actually contain. That grew: the deterministic
 * template only ever emitted headings, bold, inline code, blockquotes and
 * flat bullets, but prompts/prd-generation.system.md asks the model for
 * "a short table" in Section 2, "acceptance criteria as checkboxes" in
 * Section 3, "a table of every unverified assumption" in Section 8 and
 * says to "prefer a table row over a paragraph". Rendered by the old
 * paragraph-splitting version, those came out as literal pipes, bracketed
 * boxes and flattened lists — exactly the broken-markup look this renderer
 * exists to prevent. It is line-scanning now rather than a chain of
 * regexes, because tables and nesting need to consume several lines.
 */
export function renderPrdMarkdown(md: string): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const inline = (s: string) =>
    esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');

  /* Any line that opens with a pipe is a table row — the model sometimes
     drops the closing pipe on a long row, and cells() already tolerates it. */
  const isRow = (l: string) => /^\s*\|/.test(l);
  const isRule = (l: string) => /^\s*\|[\s:|-]+\|\s*$/.test(l);
  const cells = (l: string) =>
    l.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());

  const lines = (md ?? '').split('\n');
  const out: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    const heading = /^(#{1,4})\s+(.*)$/.exec(line);
    if (heading) {
      const level = Math.min(heading[1].length + 1, 5);
      out.push(`<h${level}>${inline(heading[2])}</h${level}>`);
      i++;
      continue;
    }

    /* A table needs its header rule on the next line; a lone piped line is
       prose and stays prose. */
    if (isRow(line) && i + 1 < lines.length && isRule(lines[i + 1])) {
      const head = cells(line);
      i += 2;
      const body: string[][] = [];
      while (i < lines.length && isRow(lines[i])) {
        body.push(cells(lines[i]));
        i++;
      }
      out.push(
        '<table><thead><tr>' +
          head.map((c) => `<th>${inline(c)}</th>`).join('') +
          '</tr></thead><tbody>' +
          body.map((r) => '<tr>' + r.map((c) => `<td>${inline(c)}</td>`).join('') + '</tr>').join('') +
          '</tbody></table>'
      );
      continue;
    }

    if (/^\s*&gt;|^\s*>/.test(esc(line))) {
      const quoted: string[] = [];
      while (i < lines.length && /^\s*>/.test(lines[i])) {
        quoted.push(inline(lines[i].replace(/^\s*>\s?/, '')));
        i++;
      }
      out.push(`<blockquote>${quoted.join('<br>')}</blockquote>`);
      continue;
    }

    if (/^\s*[-*]\s+/.test(line)) {
      const items: { depth: number; html: string }[] = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        const m = /^(\s*)[-*]\s+(.*)$/.exec(lines[i]);
        if (!m) break;
        const depth = Math.min(Math.floor(m[1].length / 2), 4);
        const task = /^\[([ xX])\]\s*(.*)$/.exec(m[2]);
        const text = task ? task[2] : m[2];
        const box = task ? `<span class="task">${task[1].trim() ? '\u2611' : '\u2610'}</span> ` : '';
        items.push({ depth, html: box + inline(text) });
        i++;
      }
      out.push(renderList(items).html);
      continue;
    }

    if (!line.trim()) {
      i++;
      continue;
    }

    const para: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() &&
      !/^(#{1,4}\s|\s*[-*]\s|\s*>|\s*\|)/.test(lines[i])
    ) {
      para.push(inline(lines[i]));
      i++;
    }
    /* Progress guard: a line that no branch above claimed (e.g. a stray
       pipe or list-like line) must still be consumed, otherwise this loop
       never advances and the tab hangs — that is exactly what a truncated
       table row in a live PRD did (run 44, finding #3). */
    if (!para.length) {
      para.push(inline(lines[i]));
      i++;
    }
    out.push(`<p>${para.join('<br>')}</p>`);
  }

  return out.join('\n');
}

/** Indentation-aware nesting. Two spaces per level, matching what the model
 *  emits; deeper indents are clamped so a stray tab cannot run away.
 *
 *  A sub-list is nested INSIDE its parent <li>, not emitted as a sibling of
 *  it — `<ul><li>a</li><ul>…</ul></ul>` is invalid and leaves the sanitiser
 *  to decide what it means. */
function renderList(items: { depth: number; html: string }[], start = 0, depth = 0): { html: string; next: number } {
  let html = '<ul>';
  let i = start;
  while (i < items.length && items[i].depth >= depth) {
    if (items[i].depth > depth) {
      const sub = renderList(items, i, items[i].depth);
      html = html.replace(/<\/li>$/, `${sub.html}</li>`);
      i = sub.next;
      continue;
    }
    html += `<li>${items[i].html}</li>`;
    i++;
  }
  return { html: html + '</ul>', next: i };
}
